export const FOOTER_URL = "https://demo2.cybersoft.edu.vn/";

export type FooterTestCase = {
  title: string;
  email: string;
  fullname: string;
  sdt: string;
  expected: string;
};

export const FOOTER_TEST_CASES: FooterTestCase[] = [
  {
    title: "TC01-Đăng kí tư vấn với đầy đủ thông tin",
    email: "vietanh1122",
    fullname: "Daibangvip123@",
    sdt: "0347631185",
    expected: "Đăng kí thành công",
  },
  {
    title: "TC02-Đăng kí tư vấn khi trường email rỗng",
    email: "",
    fullname: "Nguyen Van A",
    sdt: "0912345678",
    expected: "Email không được để trống",
  },
  {
    title: "TC03-Đăng kí tư vấn khi trường tên rỗng",
    email: "test@example.com",
    fullname: "",
    sdt: "0912345678",
    expected: "Tên không được để trống",
  },
  {
    title: "TC04-Đăng kí tư vấn khi trường số điện thoại rỗng",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "",
    expected: "Số điện thoại không được để",
  },
  {
    title: "TC05-Đăng kí tư vấn khi tất cả các trường đều rỗng",
    email: "",
    fullname: "",
    sdt: "",
    expected: "Email không được để trống",
  },
  {
    title: "TC06-Đăng kí tư vấn với email không hợp lệ (không có @)",
    email: "invalidemail.com",
    fullname: "Nguyen Van A",
    sdt: "0912345678",
    expected: "Email sai định dạng",
  },
  {
    title: "TC07-Đăng kí tư vấn với email không hợp lệ (thiếu domain)",
    email: "test@",
    fullname: "Nguyen Van A",
    sdt: "0912345678",
    expected: "Email sai định dạng",
  },
  {
    title: "TC08-Đăng kí tư vấn với email hợp lệ có dấu chấm",
    email: "test.user123@example.com",
    fullname: "Nguyen Van A",
    sdt: "0912345678",
    expected: "Đăng kí thành công",
  },
  {
    title: "TC09-Đăng kí tư vấn với số điện thoại quá ngắn",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "012",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC10-Đăng kí tư vấn với số điện thoại quá dài",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "091234567890123456789",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC11-Đăng kí tư vấn với số điện thoại chứa chữ cái",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "09ABC345678",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC12-Đăng kí tư vấn với tên rất dài",
    email: "test@example.com",
    fullname:
      "Nguyen Van A Nguyen Van B Nguyen Van C Nguyen Van D Nguyen Van E Nguyen Van F",
    sdt: "0912345678",
    expected: "Đăng kí không thành công",
  },
  {
    title: "TC13-Đăng kí tư vấn với tên chứa số",
    email: "test@example.com",
    fullname: "Nguyen Van A 12345",
    sdt: "0912345678",
    expected: "Chỉ nhập kí tự chữ",
  },
  {
    title: "TC14-Đăng kí tư vấn với tên chứa ký tự đặc biệt",
    email: "test@example.com",
    fullname: "Nguyen Van A @#$%",
    sdt: "0912345678",
    expected: "Chỉ nhập kí tự chữ",
  },
  {
    title: "TC15-Đăng kí tư vấn với email rất dài",
    email:
      "verylongemailaddresswithlotofcharacters123456789@verylongdomainname.com",
    fullname: "Nguyen Van A",
    sdt: "0912345678",
    expected: "Đăng kí thành công",
  },
  {
    title: "TC16-Đăng kí tư vấn với email hợp lệ chứa dấu cộng",
    email: "test+tag@example.com",
    fullname: "Nguyen Van A",
    sdt: "0912345678",
    expected: "Đăng kí thành công",
  },
  {
    title: "TC17-Đăng kí tư vấn với số điện thoại hợp lệ bắt đầu bằng 0",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "0987654321",
    expected: "Đăng kí thành công",
  },
  {
    title: "TC18-Đăng kí tư vấn với tên chỉ có 1 ký tự",
    email: "test@example.com",
    fullname: "A",
    sdt: "0912345678",
    expected: "Tên quá ít kí tự",
  },
  {
    title: "TC19-Đăng kí tư vấn với email chứa khoảng trắng",
    email: "test @example.com",
    fullname: "Nguyen Van A",
    sdt: "0912345678",
    expected: "Email sai định dạng",
  },
  {
    title: "TC20-Đăng kí tư vấn với tên chứa khoảng trắng ở đầu",
    email: "test@example.com",
    fullname: "  Nguyen Van A",
    sdt: "0912345678",
    expected: "Đăng kí thành công",
  },
  {
    title: "TC21-Đăng kí tư vấn với số điện thoại chứa dấu gạch ngang",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "09-1234-5678",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC22-Đăng kí tư vấn với email dưới 8 ký tự",
    email: "a@b.co",
    fullname: "Nguyen Van A",
    sdt: "0912345678",
    expected: "Đăng kí thành công",
  },
  {
    title: "TC23-Đăng kí tư vấn với tên dưới 8 ký tự",
    email: "test@example.com",
    fullname: "Nam",
    sdt: "0912345678",
    expected: "Tên quá ít kí tự",
  },
  {
    title: "TC24-Đăng kí tư vấn với SDT dưới 8 ký tự",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "091234",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC25-Đăng kí tư vấn với email và tên dưới 8 ký tự",
    email: "a@b.io",
    fullname: "Nam",
    sdt: "0912345678",
    expected: "Tên quá ít kí tự",
  },
  {
    title: "TC26-Đăng kí tư vấn với tất cả trường dưới 8 ký tự",
    email: "a@b.co",
    fullname: "Nam",
    sdt: "091234",
    expected: "Tên quá ít kí tự",
  },
  {
    title: "TC27-Đăng kí tư vấn với email dài hơn 10 ký tự",
    email: "longemail123@verylongdomain.com",
    fullname: "Nguyen Van A",
    sdt: "0912345678",
    expected: "Đăng kí thành công",
  },
  {
    title: "TC28-Đăng kí tư vấn với tên dài hơn 10 ký tự",
    email: "test@example.com",
    fullname: "Nguyen Van Anh Dung",
    sdt: "0912345678",
    expected: "Đăng kí thành công",
  },
  {
    title: "TC29-Đăng kí tư vấn với SDT dài hơn 10 ký tự",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "09123456789",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC30-Đăng kí tư vấn với email và tên dài hơn 10 ký tự",
    email: "longemail@verylongdomain.com",
    fullname: "Nguyen Van Anh Dung",
    sdt: "0912345678",
    expected: "Đăng kí thành công",
  },
  {
    title: "TC31-Đăng kí tư vấn với tất cả trường dài hơn 10 ký tự",
    email: "longemail@verylongdomain.com",
    fullname: "Nguyen Van Anh Dung",
    sdt: "09123456789",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC32-Đăng kí tư vấn với SDT chỉ chứa chữ cái",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "abcdefghij",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC33-Đăng kí tư vấn với SDT hỗn hợp chữ và số",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "0912ABC345",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC34-Đăng kí tư vấn với SDT chứa chữ cái in hoa",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "0912ABC67890",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC35-Đăng kí tư vấn với SDT chứa ký tự @",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "0912@34567",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC36-Đăng kí tư vấn với SDT chứa ký tự #",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "0912#34567",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC37-Đăng kí tư vấn với SDT chứa ký tự $",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "0912$34567",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC38-Đăng kí tư vấn với SDT chứa ký tự %",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "0912%34567",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC39-Đăng kí tư vấn với SDT chứa ký tự ^",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "0912^34567",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC40-Đăng kí tư vấn với SDT chứa ký tự &",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "0912&34567",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC41-Đăng kí tư vấn với SDT chứa ký tự *",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "0912*34567",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC42-Đăng kí tư vấn với SDT chứa ký tự (",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "0912(34567",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC43-Đăng kí tư vấn với SDT chứa ký tự )",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "0912)34567",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC44-Đăng kí tư vấn với SDT chứa ký tự _",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "0912_34567",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC45-Đăng kí tư vấn với SDT chứa ký tự +",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "0912+34567",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC46-Đăng kí tư vấn với SDT chứa ký tự =",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "0912=34567",
    expected: "Số điện thoại chưa đúng định đạng",
  },
  {
    title: "TC47-Đăng kí tư vấn với SDT chứa nhiều ký tự đặc biệt",
    email: "test@example.com",
    fullname: "Nguyen Van A",
    sdt: "0912@#$%^&",
    expected: "Số điện thoại chưa đúng định đạng",
  },
];
